version: "3.9"

services:
  db:
    image: postgres:14.6-alpine
    container_name: "orders-database"
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "orders-db"
      POSTGRES_USER: "medenzel"
      POSTGRES_PASSWORD: "qwerty"
    networks:
      - fullstack
    volumes:
      - database_postgres:/var/lib/postgresql/data
  
  api:
    build: .
    container_name: "orders-rest-api"
    environment:
      DB_USER: "medenzel"
      DB_PASSWORD: "qwerty"
      #DB_DB: "postgres"
      DB_HOST: "db"
      DB_DBNAME: "orders-db"
      DB_PORT: "5432"
      SSL_MODE: "disable"
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - fullstack

volumes:
  database_postgres:

networks:
  fullstack:
    driver: bridge
